export const GET_DATA_LOADING="GETDATALOADING";
export const GET_DATA_SUCCESS="GETDATASUCCESS";
export const GET_DATA_ERROR="GETDATAERROR";

export const ADD_DATA_LOADING="ADDDATALOADING";
export const ADD_DATA_SUCCESS="ADDDATASUCCESS";
export const ADD_DATA_ERROR="ADDDATAERROR";